Repository 2024-LIKELION-ECurator/ECurator_FE, pull requests merged in 2024-12, with the labels that each got.

#4 feat:커뮤니티 UI
  ecurator_fe/.gitignore
  ecurator_fe/README.md
  ecurator_fe/package-lock.json
  ecurator_fe/package.json
  ecurator_fe/public/images/background.png
  ecurator_fe/public/images/background.svg
  ecurator_fe/public/index.html
  ecurator_fe/public/manifest.json
  ecurator_fe/public/robots.txt
  ecurator_fe/src/App.js
  ecurator_fe/src/Routes.js
  ecurator_fe/src/components/inputs/TextInput.jsx
  ecurator_fe/src/components/lists/PostListComponent.jsx
  ecurator_fe/src/components/lists/PostListItem.jsx
  ecurator_fe/src/components/modals/deleteModal.jsx
  ecurator_fe/src/components/modals/registerModal.jsx
  ecurator_fe/src/components/modals/styled.js
  ecurator_fe/src/index.js
  ecurator_fe/src/pages/community/Poststyled.js
  ecurator_fe/src/pages/community/postList.jsx
  ecurator_fe/src/pages/community/postView.jsx
  ecurator_fe/src/pages/community/postWrite.jsx
Labels: ✨ Feature, 😊 나연

#6 feat: 캘린더 UI
  ecurator_fe/src/App.js
  ecurator_fe/src/Routes.js
  ecurator_fe/src/components/calendar/Diary.css
  ecurator_fe/src/components/calendar/Diary.jsx
  ecurator_fe/src/components/calendar/Emotion.css
  ecurator_fe/src/components/calendar/Emotion.jsx
  ecurator_fe/src/fonts/Pecita.otf
  ecurator_fe/src/fonts/font.css
  ecurator_fe/src/images/next_month.png
  ecurator_fe/src/images/prev_month.png
  ecurator_fe/src/images/stc_happy.png
  ecurator_fe/src/images/stc_joyful.png
  ecurator_fe/src/images/stc_loving.png
  ecurator_fe/src/images/stc_nervous.png
  ecurator_fe/src/images/stc_pensive.png
  ecurator_fe/src/images/stc_relieved.png
  ecurator_fe/src/images/stc_sad.png
  ecurator_fe/src/images/stc_sleepy.png
  ecurator_fe/src/images/stc_surprised.png
  ecurator_fe/src/index.js
  ecurator_fe/src/pages/calendar/CalendarPage.jsx
  ecurator_fe/src/pages/calendar/Calendarstyled.js
Labels: ✨ Feature, 😆 선우

#8 feat: 커뮤니티 기능연결
  ecurator_fe/package-lock.json
  ecurator_fe/package.json
  ecurator_fe/public/manifest.json
  ecurator_fe/src/Routes.js
  ecurator_fe/src/components/lists/PostListComponent.jsx
  ecurator_fe/src/components/lists/PostListItem.jsx
  ecurator_fe/src/components/modals/styled.js
  ecurator_fe/src/pages/community/postEdit.jsx
  ecurator_fe/src/pages/community/postList.jsx
  ecurator_fe/src/pages/community/postWrite.jsx
Labels: 📚 API, ✨ Feature, 😊 나연

#16 [Feature] 캘린더 감정 수정 api
  ecurator_fe/src/App.css
  ecurator_fe/src/components/calendar/Emotion.jsx
  ecurator_fe/src/pages/calendar/CalendarPage.jsx
  ecurator_fe/src/pages/calendar/Calendarstyled.js
Labels: 📚 API, 😆 선우
